# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af4a7c858352357f402d9eb6857be7031e78525ac3d08ca07ec7844ebbec1a15310a8395d4ce84124359c8ecba36d731c4ac78bae9abadb4ca4fc010d4aaf4e

test:
  secret_key_base: afa4629b23163dd4d254287b7a3e442f93dfd247e650522da3e702a3a44f651da940d286d3a741676f6c2ef49348a54d1012ccdc2d0d378f7774602c698cb588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
